# Generated by Django 4.2.2 on 2024-05-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="特产分类名称")),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="localblank",
                        verbose_name="特产分类图片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commdity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commdityname", models.CharField(max_length=24, verbose_name="特产名")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("form", models.CharField(max_length=128, verbose_name="成份")),
                ("content", models.TextField(blank=True, null=True, verbose_name="描述")),
                (
                    "pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="users", verbose_name="特产图片"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "审核通过")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=16, null=True, verbose_name="商家"),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="标签"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "timemes",
                    models.DateTimeField(blank=True, null=True, verbose_name="信息时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enshrine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="用户名")),
                (
                    "art_id",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="文章id"
                    ),
                ),
                (
                    "comm_id",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="商品id"
                    ),
                ),
                (
                    "enshrinetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "无效"), (1, "有效")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=16, verbose_name="用户名")),
                (
                    "score",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="评分"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rolename", models.CharField(max_length=16, verbose_name="角色名")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="姓名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("phonenumber", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "subadmin",
                    models.SmallIntegerField(
                        choices=[
                            (0, "普通使用者"),
                            (1, "申请子管理员"),
                            (2, "子管理员"),
                            (3, "系统管理员"),
                        ],
                        default=0,
                        verbose_name="管理员类别",
                    ),
                ),
                (
                    "process",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "审核通过")],
                        default=1,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.role",
                        verbose_name="角色名",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "username",
                    models.CharField(max_length=16, null=True, verbose_name="作者"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="标签"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "初步审核"), (2, "审核通过")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "timemes",
                    models.DateTimeField(blank=True, null=True, verbose_name="信息时间"),
                ),
                (
                    "commdity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.commdity",
                        verbose_name="特产",
                    ),
                ),
            ],
        ),
    ]
