# Generated by Django 4.2.2 on 2024-04-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16, verbose_name="标题")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "username",
                    models.CharField(max_length=16, null=True, verbose_name="作者"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "审核通过")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "collect",
                    models.SmallIntegerField(
                        choices=[(0, "否"), (1, "是")], default=0, verbose_name="是否收藏"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commdity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commdityname", models.CharField(max_length=24, verbose_name="商品名")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("form", models.CharField(max_length=128, verbose_name="成份")),
                (
                    "pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="users", verbose_name="商品图片"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "审核通过")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=16, null=True, verbose_name="商家"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="特产类目"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rolename", models.CharField(max_length=16, verbose_name="角色名")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="姓名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("phonenumber", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "subadmin",
                    models.SmallIntegerField(
                        choices=[
                            (0, "普通使用者"),
                            (1, "申请子管理员"),
                            (2, "子管理员"),
                            (3, "系统管理员"),
                        ],
                        default=0,
                        verbose_name="管理员类别",
                    ),
                ),
                (
                    "process",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "审核通过")],
                        default=1,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.role",
                        verbose_name="角色名",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enshrine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default=True, max_length=16, verbose_name="用户名"),
                ),
                (
                    "enshrinetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "无效"), (1, "有效")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.article",
                        verbose_name="文章id",
                    ),
                ),
                (
                    "commdity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.commdity",
                        verbose_name="商品id",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commdity",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.food",
                verbose_name="特产分类",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="commdity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.commdity",
                verbose_name="商品",
            ),
        ),
    ]
