# Generated by Django 4.2.2 on 2024-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commdity",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
    ]
