# Generated by Django 4.2.2 on 2024-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="时间")),
                ("name", models.CharField(max_length=255, verbose_name="发送者")),
            ],
        ),
    ]
