# Generated by Django 4.2.2 on 2024-05-08 23:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="内容"),
        ),
    ]
