# Generated by Django 4.2.2 on 2024-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_commdity_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="collect",
        ),
        migrations.AddField(
            model_name="article",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commdity",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
