# Generated by Django 4.2.2 on 2024-05-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_message_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, verbose_name="公司名称")),
                ("company_type", models.CharField(max_length=255, verbose_name="公司类型")),
                (
                    "representative_name",
                    models.CharField(max_length=255, verbose_name="法定代表人姓名"),
                ),
                ("id_number", models.CharField(max_length=18, verbose_name="法人身份证号码")),
                ("id_expiration_date", models.DateField(verbose_name="法人身份证有效期")),
                ("contact_phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "actual_office_address",
                    models.CharField(max_length=255, verbose_name="实际办公地址"),
                ),
            ],
        ),
    ]
