# Generated by Django 4.2.2 on 2024-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_article_collect_article_is_favorite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="commdity",
            name="is_favorite",
        ),
        migrations.DeleteModel(
            name="Enshrine",
        ),
    ]
