# Generated by Django 4.2.2 on 2024-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_article_is_favorite_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enshrine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="用户名")),
                (
                    "art_id",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="文章id"
                    ),
                ),
                (
                    "comm_id",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="商品id"
                    ),
                ),
                (
                    "enshrinetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "无效"), (1, "有效")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
    ]
