# Generated by Django 4.2.2 on 2024-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="密码"
            ),
        ),
    ]
