# Generated by Django 4.2.2 on 2024-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_merchant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="password",
            field=models.CharField(max_length=255, verbose_name="密码"),
        ),
    ]
