# Generated by Django 4.2.2 on 2024-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_enshrine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commdity",
            name="price",
        ),
        migrations.AlterField(
            model_name="commdity",
            name="commdityname",
            field=models.CharField(max_length=24, verbose_name="特产名"),
        ),
        migrations.AlterField(
            model_name="commdity",
            name="pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="users", verbose_name="特产图片"
            ),
        ),
    ]
