# Generated by Django 4.2.2 on 2024-04-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_commdity_price_alter_commdity_commdityname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="特产分类名称")),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="localblock",
                        verbose_name="特产分类图片",
                    ),
                ),
            ],
        ),
    ]
