# Generated by Django 4.2.2 on 2024-05-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_merchant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="company_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "有限责任公司 "),
                    (1, "股份有限公司"),
                    (2, "无限公司"),
                    (3, "两合公司"),
                    (4, "股份两合公司"),
                ],
                max_length=255,
                verbose_name="公司类型",
            ),
        ),
    ]
