# Generated by Django 4.2.2 on 2024-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=128, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="localblank", verbose_name="特产分类图片"
            ),
        ),
    ]
