# Generated by Django 4.2.2 on 2024-05-26 16:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_merchant_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="内容"),
        ),
    ]
