# Generated by Django 4.2.2 on 2024-04-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_article_title_alter_choice_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="commdity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.commdity",
                verbose_name="特产",
            ),
        ),
    ]
