# Generated by Django 4.2.2 on 2024-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
    ]
