# Generated by Django 4.2.2 on 2024-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_article_commdity"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="commdity",
            name="tag",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="标签"
            ),
        ),
    ]
