# Generated by Django 4.2.2 on 2024-04-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_article_tag_commdity_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commdity",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.food",
                verbose_name="特产分类",
            ),
        ),
    ]
