# Generated by Django 4.2.2 on 2024-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_commdity_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commdity",
            name="food",
        ),
    ]
