# Generated by Django 4.2.2 on 2024-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_commdity_food"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=16, verbose_name="用户名")),
                (
                    "score_user",
                    models.DecimalField(
                        decimal_places=4, max_digits=4, verbose_name="用户评分"
                    ),
                ),
                (
                    "score_item",
                    models.DecimalField(
                        decimal_places=4, max_digits=4, verbose_name="商品评分"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Food",
        ),
    ]
