# Generated by Django 4.2.2 on 2024-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_recommend_delete_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommend",
            name="score_item",
        ),
        migrations.RemoveField(
            model_name="recommend",
            name="score_user",
        ),
        migrations.AddField(
            model_name="recommend",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=4, null=True, verbose_name="评分"
            ),
        ),
    ]
