# Generated by Django 4.2.2 on 2024-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_recommend_score_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommend",
            name="score",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="评分"
            ),
        ),
    ]
