# Generated by Django 4.2.2 on 2024-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_recommend_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "待审核"), (1, "初步审核"), (2, "审核通过")],
                default=0,
                verbose_name="审核状态",
            ),
        ),
    ]
