# Generated by Django 4.2.2 on 2024-04-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_commdity_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="commdity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.commdity",
                verbose_name="商品",
            ),
        ),
    ]
