# Generated by Django 4.2.2 on 2024-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_article_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="message",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="备注"
            ),
        ),
        migrations.AddField(
            model_name="commdity",
            name="message",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="备注"
            ),
        ),
    ]
