# Generated by Django 4.2.2 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_article_message_commdity_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="timemes",
            field=models.DateTimeField(blank=True, null=True, verbose_name="信息时间"),
        ),
        migrations.AddField(
            model_name="commdity",
            name="timemes",
            field=models.DateTimeField(blank=True, null=True, verbose_name="信息时间"),
        ),
    ]
